"""igrate_name

Revision ID: 3fbf853fcc1f
Revises: 08e0b17434c8
Create Date: 2023-04-13 16:04:21.348754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbf853fcc1f'
down_revision = '08e0b17434c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
