"""igrate_name

Revision ID: b5492ba60bac
Revises: 614ae7c34703
Create Date: 2023-04-13 18:24:57.574464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5492ba60bac'
down_revision = '614ae7c34703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like_blog', sa.Column('create_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like_blog', 'create_date')
    # ### end Alembic commands ###
